
amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.08
    alpha2: 0.08
    alpha3: 0.08
    alpha4: 0.08
    alpha5: 0.08
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 5.0
    laser_min_range: 0.2
    laser_model_type: "likelihood_field"
    max_beams: 100
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.02
    pf_z: 0.85
    recovery_alpha_fast: 0.05
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.02
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.06
    update_min_d: 0.025
    z_hit: 0.7
    z_max: 0.01
    z_rand: 0.059
    z_short: 0.24

    # Initial Pose
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_yaw: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    BaseObstacle:
      scale: 0.02
      sum_scores: false
    BaseObstacle/class: BaseObstacle
    GoalAlign:
      aggregation_type: last
      scale: 0.0
    GoalAlign/class: GoalAlign
    GoalDist:
      aggregation_type: last
      scale: 24.0
    GoalDist/class: GoalDist
    Oscillation:
      scale: 1.0
      x_only_threshold: 0.05
    Oscillation/class: Oscillation
    PathAlign:
      aggregation_type: last
      scale: 0.0
    PathAlign/class: PathAlign
    PathDist:
      aggregation_type: last
      scale: 32.0
    PathDist/class: PathDist
    RotateToGoal:
      scale: 32.0
    RotateToGoal/class: RotateToGoal
    acc_lim_theta: 3.2
    acc_lim_x: 4.5
    acc_lim_y: 0.0
    controller_frequency: 20.0
    critics:
    - RotateToGoal
    - Oscillation
    - BaseObstacle
    - GoalAlign
    - PathAlign
    - PathDist
    - GoalDist
    debug_trajectory_details: true
    decel_lim_theta: -3.2
    decel_lim_x: -2.5
    decel_lim_y: 0.0
    discretize_by_time: false
    goal_checker_name: dwb_plugins::SimpleGoalChecker
    local_controller_plugin: dwb_core::DWBLocalPlanner
    max_speed_xy: 3.26
    max_vel_theta: 1.0
    max_vel_x: 1.26
    max_vel_y: 0.0
    min_speed_theta: 0.0
    min_speed_xy: 0.0
    min_theta_velocity_threshold: 0.001
    min_vel_x: 0.0
    min_vel_y: 0.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    prune_distance: 1.0
    prune_plan: true
    publish_cost_grid_pc: false
    publish_evaluation: true
    publish_global_plan: true
    publish_local_plan: true
    publish_trajectories: true
    publish_transformed_plan: true
    sim_time: 1.0
    trajectory_generator_name: dwb_plugins::StandardTrajectoryGenerator
    transform_tolerance: 0.2
    use_sim_time: true
    vx_samples: 20
    vy_samples: 5
    xy_goal_tolerance: 0.25
    yaw_goal_tolerance: 0.25
    short_circuit_trajectory_evaluation: True
    trans_stopped_velocity: 0.25
    slowing_factor: 5.0
    lookahead_time: -1.0
    stateful: True

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      global_frame: odom # map
      plugin_names: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::VoxelLayer", "nav2_costmap_2d::InflationLayer"]
      rolling_window: true
      update_frequency: 7.5
      publish_frequency: 7.5
      width: 2
      height: 2
      resolution: 0.025
      robot_radius: 0.16
      inflation_layer:
        enabled: true
        inflate_unknown: false
        inflation_radius: 0.4
        cost_scaling_factor: 15.0
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel_layer:
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 10
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /camera/aligned_depth_to_color/points
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      plugin_names: ["static_layer", "obstacle_layer", "voxel_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::StaticLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::VoxelLayer", "nav2_costmap_2d::InflationLayer"]
      robot_radius: 0.16
      update_frequency: 7.5
      publish_frequency: 7.5
      inflation_layer:
        inflation_radius: 0.4
        cost_scaling_factor: 15.0
      obstacle_layer:
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel_layer:
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 10
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /camera/aligned_depth_to_color/points
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"

planner_server:
  ros__parameters:
    use_sim_time: False
    tolerance: 0.0
    use_astar: false

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

robot_state_publisher:
  ros__parameters:
    use_sim_time: False
